<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Dave Lang_company-logo-img</name>
   <tag></tag>
   <elementGuidId>5def6de7-1975-4c6a-97e1-0b9b8ed153d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/table/tbody/tr/td/div/div/div/div/nav/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.company-logo-img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://api-content-b.staging.creditsights.com/resources/587176/CS_log.png</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>company-logo-img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/table[@class=&quot;print-container&quot;]/tbody[@class=&quot;print-container__body&quot;]/tr[1]/td[1]/div[1]/div[@class=&quot;page-container standard-page&quot;]/div[@class=&quot;site-header&quot;]/div[@class=&quot;site-header-nav pinned&quot;]/nav[@class=&quot;navigation-bar&quot;]/div[@class=&quot;company-logo&quot;]/a[@class=&quot;company-logo-link active&quot;]/img[@class=&quot;company-logo-img&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/table/tbody/tr/td/div/div/div/div/nav/div/a/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://api-content-b.staging.creditsights.com/resources/587176/CS_log.png')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
   </webElementXpaths>
</WebElementEntity>
