<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Amarveer SinghAndrew BeltonAndrew Br_f69fc1</name>
   <tag></tag>
   <elementGuidId>195464a4-677e-41d8-b4d4-84667d42732e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#analystSelect</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='analystSelect']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>analystSelect</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control small selectpicker</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-live-search</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-none-selected-text</name>
      <type>Main</type>
      <value>Select author(s)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-none-results-text</name>
      <type>Main</type>
      <value>No author found with {0}</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>analystSelected(this, event)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-98</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
						
					Amarveer SinghAndrew BeltonAndrew BradyAndrew FlintoffAndrew MoulderAndy DeVries, CFAAndy Li, CFAAnneli LefrancAshley TaylorAshwin TiruvasuAustin BaunBelle YangBen MorganBrayan LaiBrendan KeevanBrian FosterBrian StudiosoCallum PostlethwaiteCarlos RazuriCharles Johnston, CFACharlotta ChungCheong Yin Chin, CFAChris SeterChris Snow, CFAChris Ucko, CFACindy Liu, FRMCreditSights Risk Products TeamCreditSights StaffCreditSights Strategy TeamDan CalandrilloDavid Bussey, CFADavid MarshallDavid Shnaps, CFADavid WattsEmily PaolinoEric Axon, CFAEric NgErik WisentanerErin LyonsFrank Lee, CFAGeorge MiltonGlenn Reynolds, CFAHelen RodriguezHenry PflegerHitin AnandHoward SitzerHunter Martin, CFAInga KolasJake Leiby, CFAJames DunnJames Goldstein, CFAJames WilsonJason TanJeff Khasin, CFAJennifer BryanJesse RosenthalJesse WasilyJim WilliamsonJin Mei YeJoel LiauwJoey BortfeldJohn RaymondJordan Chalfin, CFAJosh Esterov, CFAJosh OlazabalJoshua WasserKai Gilkes, Ph.D.Kevin ChunLakshmanan R, CFA, FRMLarissa KnepperLaura Berman, CFALauren A. HollandLouise PurtleLuther Chai, CFAMario BarbagalloMariya Nurgaziyeva, CFAMark Chapman, CFAMary Pollock, CFAMaryum AliMatt ZlotoMax CapelMichael ConnollyMichael O’BrienMiguel SilvestriNathan Wenger, CFANeill KeaneyNew Analyst GBNick MogliaOliver BurkeOlu ShoyoyePaola BiraschiPat LubyPatrick GinnPengyu Xiong, CFAPeter PetasPeter Simon, CFAPramod ShenoiPuja KariaRahul GandhiRahul VohraRaymond TamRobert DeaneRobin GreenhalghRoger KingRohan KapurRonald VerasSandra Chow, CFASimon AdamsonSusan LewisSzeto Kah KeongTomas HirstWen Li, CFAYim Yi XiangYustina Quek, CFAAdam CohenAdam SteerAditya MithalAidas BaublysAlex PapazianAlix De RaucourtAllen ChachkesAmal DuttAmelia SugiartoAng Ben YouAnja KingAnju JainAnkita ManiktalaAnna AndreevaAnna Basanskaya, CFAArjun SinghArnau Lopez, CFAArnie BermanAtish KakodkarAugustin MonnoyeurBaylor LancasterBen JosephsBondScore SupportBrian M. Gibbons, Jr., CFABrian YelvingtonCatherine ShinCedrick CassinCeleste ZhangCharles-Henri BoivinChi Sun (Nelson) ChowChris Taggert, CFAChris ValentinoChristian StrackeClaire LongCole CallahanCraig Guttenplan, CFADan WardDarcy TravlosDavid GaribaldiDavid HendlerDavid ReichDiya SawhnyDot Matthews, JDEdward MuiEdward TsaiElisha FigdorEric MoskowitzEugene WangFabian HollanderFara LupianoFernando BarajasFilip TerFrancis NgFrancois Nicolas, CFAGeoffrey Wan, CFAGilead SpivackGita BalGreg Jones, CFAGreg NissHana GaletovaHesham ShaabanHiva GhiriIsaac Codrey CFA, CAIAIsmael PiliJack RogoffJake Newman, CFAJames RankJassie Singh, CFAJay MayersJeff Wichmann, CFAJerry ZhaoJim BaltzJim SullivanJohn Poehling, Jr.Jonathan ChatelainJordan MeighanJoseph Di Carlo, CFAJoseph H. Phillips, CFAKaren KlapperKristina ReganKristine LanspaLeandro GublerLia CromwellLindsay P. GibbonsLouisa MartinMarcos ArceMark CheokMark KogelMartha UckoMaryanne HennesseyMatt KarnesMatthew Phan, CFAMegha KhandujaMichael Chakardjian, CFAMichael FindleyMichael Mistras, CFAMichael Smith, CFAMichael T. KaagMiguel MolinaMike BrownMike WardNalin SayalNanakarina KwofieNesche YazganNicholas Yap, CFANicolas Rios, CFANisha VidaniNivedita BajajNora DietschPatricia LeePatrizia D’AmicoPearl ChangPeter BoozanPhilip deGrouchyPhilippe PicagnePrerna KapoorPri de SilvaQaim WynterRaghav BhandariRamanuj SarkarRashedul DinReena MithalRichard Briggs, CFARichard HofmannRicky KotechaRidhima SuriRob HainesRoger GuestSam GoodyearSarah RowinSaudamini MattuSaumya RanaScott GreensteinScott SableSean JutahkitiSeong-Min KimShaily  PathakSharon McGarvey, CFASimon AtkinsonSimon BallardSophie LindstromSpencer SiinoStephen SikoraSteven ZausnerSuela NakoSui DanSuzanne Cassidy, CFASuzanne ChamberlainTed PolitoThomas SwiftTorstein JorstadUdit PatwardhanUdith SikandVictoria AshworthViraajj BadhwarWei WuWeiwei HuangWill BenedictXin LiuYamah OmarYin ChoiZhiping (Ping) Zhao, Ph.D.</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;analystSelect&quot;)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/CreateSFAArticle/Page_Quark Publishing Platform Web Client/iframe_Sorry your browser does not support _d983a2</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='analystSelect']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Authors'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select author(s)'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Amarveer Singh'])[2]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
   </webElementXpaths>
</WebElementEntity>
